// Generated by server/scripts/gen_saijiki_ts.py from saijiki.py. Do not edit by hand.
import type { SaijikiCategory } from './saijiki';

export const GENERATED_SAIJIKI: SaijikiCategory[] = [
	{
		key: 'katachi',
		label: 'かたち',
		en: 'forms',
		words: ['円', '楕円', '三角', '四角', '線', '弧', '点', '雲形']
	},
	{
		key: 'katamuki',
		label: 'かたむき',
		en: 'angles',
		words: ['水平', '垂直', '斜め', '右上がり', '右下がり', '回転']
	},
	{
		key: 'tezawari',
		label: 'てざわり',
		en: 'touches',
		words: ['銀筆', '鉛筆', 'ペン', 'ロットリング', 'クレヨン', 'チョーク', '細筆', '太筆', '油彩', 'ビュラン', 'ドライポイント', 'コンピュータ']
	},
	{
		key: 'tsuranari',
		label: 'つらなり',
		en: 'continuity',
		words: ['実線', '破線', '点線', '一点鎖線']
	},
	{
		key: 'omote',
		label: 'おもて',
		en: 'surfaces',
		words: ['空', '塗り', '薄墨', '粒', '点描', '平行線', '交差線', 'アクアチント', '濃い', '薄い']
	},
	{
		key: 'ji',
		label: 'じ',
		en: 'grounds',
		words: ['紙', '和紙', '薄墨地', '木炭地', 'カンバス', '画用紙', 'メゾチント']
	},
	{
		key: 'iro',
		label: 'いろ',
		en: 'colors',
		words: ['白', '黒', '青', '赤', '緑', '灰', '黄', '橙', '紫']
	},
	{
		key: 'yuragi',
		label: 'ゆらぎ',
		en: 'movements',
		words: ['細かく', '大きく', 'ゆっくり', '速く', '揺れる', '波打つ', 'にじみ']
	},
	{
		key: 'basho',
		label: 'ばしょ',
		en: 'places',
		words: ['上', '下', '中心', '左端', '右端', '上端', '下端', '始点', '終点', '途中', '隅']
	},
	{
		key: 'ugoki',
		label: 'うごき',
		en: 'motions',
		words: ['置く', '並べる', '引く', '散らす', '埋める', '敷き詰める']
	},
	{
		key: 'jun',
		label: 'じゅん',
		en: 'order',
		words: ['交互に', '順に']
	},
	{
		key: 'wariai',
		label: 'わりあい',
		en: 'proportions',
		words: ['縦長', '横長', '全幅', '半幅', '半円', '上弦', '下弦', '三日月']
	},
	{
		key: 'aida',
		label: 'あいだ',
		en: 'relations',
		words: ['沿う', '触れない', '切る', '間に', '触れる', 'つながる', '鏡写し']
	},
];

export const GENERATED_SAIJIKI_EN: SaijikiCategory[] = [
	{
		key: 'katachi',
		label: 'かたち',
		en: 'forms',
		words: ['circle', 'ellipse', 'triangle', 'square', 'line', 'arc', 'point', 'cloudform']
	},
	{
		key: 'katamuki',
		label: 'かたむき',
		en: 'angles',
		words: ['horizontal', 'vertical', 'diagonal', 'rising', 'falling', 'rotated']
	},
	{
		key: 'tezawari',
		label: 'てざわり',
		en: 'touches',
		words: ['silverpoint', 'pencil', 'pen', 'rotring', 'crayon', 'chalk', 'fine-brush', 'thick-brush', 'oil paint', 'burin', 'drypoint', 'computer']
	},
	{
		key: 'tsuranari',
		label: 'つらなり',
		en: 'continuity',
		words: ['solid', 'dashed', 'dotted', 'dash-dot']
	},
	{
		key: 'omote',
		label: 'おもて',
		en: 'surfaces',
		words: ['empty', 'flat', 'pale ink wash', 'grain', 'stipple', 'hatch', 'crosshatch', 'aquatint', 'dense', 'faint']
	},
	{
		key: 'ji',
		label: 'じ',
		en: 'grounds',
		words: ['paper', 'washi', 'ink wash ground', 'charcoal ground', 'canvas', 'drawing paper', 'mezzotint']
	},
	{
		key: 'iro',
		label: 'いろ',
		en: 'colors',
		words: ['white', 'black', 'blue', 'red', 'green', 'gray', 'yellow', 'orange', 'purple']
	},
	{
		key: 'yuragi',
		label: 'ゆらぎ',
		en: 'movements',
		words: ['fine', 'large', 'slowly', 'quickly', 'swaying', 'undulating', 'bleeding']
	},
	{
		key: 'basho',
		label: 'ばしょ',
		en: 'places',
		words: ['top', 'bottom', 'center', 'left-edge', 'right-edge', 'top-edge', 'bottom-edge', 'start', 'end', 'partway', 'corner']
	},
	{
		key: 'ugoki',
		label: 'うごき',
		en: 'motions',
		words: ['place', 'line-up', 'draw', 'scatter', 'fill', 'tile']
	},
	{
		key: 'jun',
		label: 'じゅん',
		en: 'order',
		words: ['alternating', 'in order']
	},
	{
		key: 'wariai',
		label: 'わりあい',
		en: 'proportions',
		words: ['tall', 'wide', 'full-width', 'half-width', 'semicircle', 'waxing', 'waning', 'crescent']
	},
	{
		key: 'aida',
		label: 'あいだ',
		en: 'relations',
		words: ['along', 'not touching', 'cutting', 'between', 'touching', 'connected', 'mirrored']
	},
];
