"""SVG document structure and metadata for the default render engine."""

from __future__ import annotations

import json
import re
from typing import Any
from xml.sax.saxutils import escape

import svgwrite

from ...plugins import CanvasSize
from ...schema import CLOSED_SHAPES, CanvasGroundSpec, CanvasSpec, Instruction, Score

# Keep the legacy constant import path while consumers move to the neutral owner.
from ..profiles import SVG_PROFILES as SVG_PROFILES
from ..profiles import normalize_svg_profile as _normalize_svg_profile


def _score_canvas_aspect(score: Score) -> str:
    if isinstance(score.canvas, CanvasSpec):
        return score.canvas.aspect
    return str(score.canvas or "square")


def _score_canvas_ground(score: Score) -> CanvasGroundSpec | None:
    if isinstance(score.canvas, CanvasSpec):
        ground = score.canvas.ground
        if ground is not None and ground.material != "plain":
            return ground
    return None


def build_texture_metadata(score: Score, *, svg_profile: str | None = None) -> dict:
    profile = _normalize_svg_profile(svg_profile)
    ground = _score_canvas_ground(score)
    surfaces = []
    for idx, ins in enumerate(score.instructions):
        # The same three conditions `_has_surface_texture` uses. Without the
        # primitive test this reported a texture on every line and arc that
        # carried one -- 53.4% of all surfaces in production -- and the render
        # JSON said a texture was there that not one pixel of the SVG showed.
        if (
            ins.surface is not None
            and ins.surface.texture not in ("none", "solid")
            and ins.primitive in CLOSED_SHAPES
        ):
            surfaces.append(
                {
                    "instruction_index": idx,
                    "texture": ins.surface.texture,
                    "density": ins.surface.density,
                    "opacity": ins.surface.opacity,
                }
            )
    metadata = {
        "render_texture_version": "1",
        "render_texture_profile": profile,
        "texture_degraded": profile == "compat" and bool(surfaces),
    }
    if ground is not None:
        metadata["render_canvas_ground"] = ground.model_dump(
            mode="json", exclude_none=True
        )
    if surfaces:
        metadata["render_surface_textures"] = surfaces
    return metadata


def _safe_svg_id(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("._-")
    if not safe:
        safe = "item"
    if not re.match(r"[A-Za-z_]", safe):
        safe = f"inku_{safe}"
    return safe


def _instruction_svg_id(ins: Instruction, ins_idx: int) -> str:
    parts = [f"instruction_{ins_idx:03d}", ins.primitive, ins.color, ins.weight]
    if ins.style != "solid":
        parts.append(ins.style)
    return _safe_svg_id("_".join(parts))


def _mark_svg_id(ins: Instruction, ins_idx: int, mark_idx: int) -> str:
    return _safe_svg_id(f"mark_{ins_idx:03d}_{mark_idx:03d}_{ins.primitive}")


def _inject_svg_document_metadata(svg: str, *, profile: str) -> str:
    title = f"inku render ({profile} SVG)"
    desc = (
        "Generated by inku. Groups and IDs are included for vector editing."
        if profile == "editable"
        else "Generated by inku. Portable SVG output."
    )
    metadata = json.dumps(
        {"generator": "inku", "svg_profile": profile},
        ensure_ascii=False,
        separators=(",", ":"),
    )
    document_metadata = (
        f"<title>{escape(title)}</title>"
        f"<desc>{escape(desc)}</desc>"
        f'<metadata id="inku_metadata">{escape(metadata)}</metadata>'
    )
    return re.sub(r"(<svg\b[^>]*>)", r"\1" + document_metadata, svg, count=1)



def _new_svg_drawing(canvas: CanvasSize) -> svgwrite.Drawing:
    return svgwrite.Drawing(
        size=(canvas.width, canvas.height),
        viewBox=f"0 0 {canvas.width} {canvas.height}",
    )


def _build_root_groups(
    dwg: svgwrite.Drawing,
    canvas: CanvasSize,
    bg: str,
    ground_layer: Any,
    *,
    structured: bool,
) -> tuple[Any | None, Any, Any]:
    if structured:
        artboard = dwg.g(id="inku_artboard")
        background = dwg.g(id="layer_00_background")
        background.add(
            dwg.rect(
                insert=(0, 0),
                size=(canvas.width, canvas.height),
                fill=bg,
                id="background",
            )
        )
        content = dwg.g(id="layer_10_content")
        presence_content = dwg.g(id="layer_20_presence")
        artboard.add(background)
        if ground_layer is not None:
            artboard.add(ground_layer)
        artboard.add(content)
        artboard.add(presence_content)
        return artboard, content, presence_content

    dwg.add(dwg.rect(insert=(0, 0), size=(canvas.width, canvas.height), fill=bg))
    if ground_layer is not None:
        dwg.add(ground_layer)
    clip_id = "canvas-clip"
    clip = dwg.defs.add(dwg.clipPath(id=clip_id))
    clip.add(dwg.rect(insert=(0, 0), size=(canvas.width, canvas.height)))
    content = dwg.g(clip_path=f"url(#{clip_id})")
    return None, content, content


def _attach_root_groups(
    dwg: svgwrite.Drawing,
    artboard: Any | None,
    content: Any,
    *,
    structured: bool,
) -> None:
    if structured:
        assert artboard is not None
        dwg.add(artboard)
    else:
        dwg.add(content)


def _inject_extra_defs(svg: str, fragments: list[str]) -> str:
    extra_defs_xml = "".join(fragment for fragment in fragments if fragment)
    if not extra_defs_xml:
        return svg
    if "<defs />" in svg:
        return svg.replace("<defs />", f"<defs>{extra_defs_xml}</defs>", 1)
    if "<defs/>" in svg:
        return svg.replace("<defs/>", f"<defs>{extra_defs_xml}</defs>", 1)
    return svg.replace("<defs>", f"<defs>{extra_defs_xml}", 1)
