def core_api_version() -> str: ...
def render_engine_id() -> str: ...
def render_engine_version() -> str: ...
def default_color_map_json() -> str: ...
def render(request_json: str) -> tuple[str, str]: ...
def render_with_resources(request_json: str, resources_json: str) -> tuple[str, str]: ...
