def core_api_version() -> str: ...
def render_engine_id() -> str: ...
def render_engine_version() -> str: ...
def default_color_map_json() -> str: ...
def pipeline_canvas_registry() -> str: ...
def pipeline_render_saved(input_bytes: bytes) -> bytes: ...
def pipeline_resolve_macro_catalog(input_bytes: bytes) -> bytes: ...
def pipeline_resolve_palette(input_bytes: bytes) -> bytes: ...
def pipeline_step(snapshot_bytes: bytes, input_envelope_bytes: bytes) -> bytes: ...
def pipeline_version_report() -> str: ...
def render(request_json: str) -> tuple[str, str]: ...
def render_with_resources(request_json: str, resources_json: str) -> tuple[str, str]: ...
