"""English instruction-language support."""

from __future__ import annotations


from ..composer import SYSTEM_PROMPT_EN as STAGE2_PROMPT
from ..ddl_expander import expand_intermediate_ddl
from ..interpreter import SYSTEM_PROMPT_EN as STAGE1_PROMPT
from .base import InstructionLanguageSupport

COERCE_MARKERS = {
    "material_weight_hints": (
        (("rotring",), "rotring"),
        (("pencil",), "pencil"),
        (("crayon",), "crayon"),
        (("chalk",), "chalk"),
        (("fine-brush", "fine brush"), "brush_thin"),
        (("thick-brush", "thick brush"), "brush_thick"),
        (("ink-wash", "ink wash"), "brush_thin"),
    ),
    "color_markers": (
        (("white",), "white"),
        (("black", "dark", "shadow", "ink"), "black"),
        (("blue", "sky", "water", "lake", "sea", "rain", "cold"), "blue"),
        (("red",), "red"),
        (("green", "forest", "leaf", "grass", "moss", "bamboo", "garden", "scent", "fragrance"), "green"),
        (("gray", "grey"), "gray"),
        (("yellow", "gold"), "yellow"),
        (("orange", "lantern"), "orange"),
        (("purple", "violet", "lilac"), "purple"),
    ),
    "negated_color_markers": {
        "green": ("not green", "avoid green", "without green", "no green"),
    },
    "shape_intent_markers": (
        (("polygon", "crystal", "mineral", "hard shard"), "polygon"),
        (("mountain", "sharp", "peak", "ridge", "triangle"), "triangle"),
        (("arc", "spiral", "coil", "curl", "ripple"), "arc"),
        (("paper", "fragment", "fold", "shard", "square"), "square"),
    ),
    "motif_intent_markers": (
        (("leaf", "fallen leaves", "autumn leaves", "dry leaves"), "leaf_cluster"),
        (("paper", "fragment", "shard", "letter"), "paper_shard"),
        (("ripple", "spiral", "coil"), "ripple_knot"),
        (("mountain", "ridge", "peak"), "mountain_sign"),
    ),
    "atmospheric_effect": (
        "membrane", "haze", "fog", "mist", "atmosphere", "soft light", "scent", "fragrance",
        "five-sense", "reflection",
    ),
    "quiet_density": (
        # "one " was here and matched the number itself: "one hundred twenty lines"
        # tripped the quiet-density governor and lost the very count it asked for.
        "quiet", "silence", "negative space", "thin", "pale", "slight", "single",
        "presence", "trace", "memory", "forgotten", "shadow", "cold", "transparent", "membrane",
        "haze", "fog", "mist", "blur", "low cloud", "pressing down",
    ),
    "vertical_density": ("rain", "snow", "falling", "vertical", "top to bottom"),
    "motion": (
        "moving", "sway", "flow", "fade", "dissolve", "stretch", "turn", "wind", "wave",
        "goes home first", "returns first", "low cloud", "pressing down", "shadow only", "blur", "tear",
        "trembling", "single drop", "remain", "remains", "drift", "drifts", "drifting",
        "pull", "pulls", "toward", "upper-right focus",
        "before", "after", "again and again", "as if", "at once", "bow", "bows", "sound", "sounds",
        "wake", "rose", "raised", "appeared", "disappeared", "returned", "shifted",
        "whistle", "whistled", "dog moved", "flock moved", "listen", "tilted", "lit up", "bell",
        "moved his feet", "under the table", "father did", "father's father", "line of birds",
        "grandmother", "planted", "mango", "tree still stands",
    ),
    "colorful": ("festival", "colored paper", "fruit", "neon", "sunset", "colorful", "multi-color"),
    "leaf_grain": ("leaf", "autumn forest", "fallen leaves", "autumn leaves", "dry leaves"),
    "silence_layer": ("abandoned school", "corridor", "long silence"),
    "hard_edge": (
        "factory", "steel frame", "rust", "girder", "warehouse", "grid", "cut", "cuts", "brick",
        "parking-lot", "parking lot", "rectangle",
    ),
    "playful_motion": ("bicycle", "slope", "petal", "colored paper", "wind chime"),
    "edge_light": ("night", "black", "dark", "lighthouse", "only light", "sea", "glass", "neon"),
    "strong_edge_light": ("lighthouse", "only light", "cutting light", "single beam"),
    "vanishing_trace": ("breath", "footprint", "fade", "fading", "dissolve", "outline", "memory", "trace", "far"),
    "rhythm": (
        "rhythm", "dance", "dancers", "moved his feet", "under the table", "bounce", "alternating", "playful", "joy", "celebration",
        "quilt", "patchwork", "handmade", "folk",
    ),
    "visual_event": (
        "collision", "burst", "focus", "turning point", "pop", "release",
        "wandering", "fading", "trembling", "single drop", "goes home first", "curling",
        "low cloud", "pressing down", "shadow only", "blur", "tear",
        "breath", "reflect", "reflection", "reflections", "lighthouse", "only light", "footprint", "outline",
        "unravel", "petal", "quiet", "negative space", "horizon", "prairie", "open road",
        "jazz", "syncopated", "backbeat", "blue-note", "improvised",
        "dark pause", "pause", "transparent reflections", "bus-stop window",
        "quilt", "patchwork", "handmade", "folk", "scent", "fragrance", "grass", "parking-lot", "parking lot",
        "diagonal", "rectangle", "red interruption", "chalk", "dust",
        "before", "after", "again and again", "as if", "at once", "bow", "bows", "sound", "sounds",
        "wake", "cloth", "applause", "rose", "river surface", "another road", "same beat", "shifted",
        "appeared", "disappeared", "returned", "slightly changed", "whistle", "whistled", "dog moved",
        "flock moved", "listen", "drop", "tatami", "tilted", "whole room", "departure board", "lit up", "bell",
        "moved his feet", "under the table", "father did", "father's father", "line of birds",
        "grandmother", "planted", "mango", "tree still stands",
    ),
    "ma_pressure": (
        "negative space", "ma", "empty space", "presence", "pull", "push", "avoid",
        "paper", "newspaper", "letter", "sheet", "wind", "crossing", "wander", "drift",
        "horizon", "prairie", "open road",
        "jazz", "syncopated", "blue-note", "city corner",
        "dark pause", "pause", "transparent", "reflections", "sparse", "dust", "chalk",
        "before", "after", "again and again", "as if", "at once", "bow", "sounds", "wake", "cloth",
        "river surface", "another road", "whistle", "flock", "tatami", "whole room", "under the table",
    ),
    "semantic_visual_event_hints": (
        (("open road", "upper-right focus"), "visual event preserved as a road-pull focus accent"),
        (("blue-note", "dark pause", "pause"), "visual event preserved as a blue-note pause accent"),
        (
            ("transparent reflection", "transparent reflections", "transparent membrane", "transparent", "faint reflection", "reflection"),
            "visual event preserved as a reflected accent",
        ),
        (("red interruption", "interruption"), "visual event preserved as a small interruption accent"),
        (("brick wall dust", "chalk", "dust"), "visual event preserved as chalk dust tension"),
        (("before", "after", "again and again", "as if", "at once"), "visual event preserved as temporal hinge"),
        (("bow", "bows", "sound", "sounds", "wake", "cloth", "applause"), "visual event preserved as action residue"),
        (("whistled", "dog moved", "flock moved", "listen"), "visual event preserved as chain reaction"),
        (("drop", "tatami", "tilted", "whole room"), "visual event preserved as tilted-room drop"),
        (("departure board", "lit up", "bell"), "visual event preserved as pre-bell light hinge"),
        (("festival", "dancers", "moved his feet", "under the table"), "visual event preserved as hidden foot rhythm"),
        (("bows", "father did", "father's father", "each morning"), "visual event preserved as three-generation bow sequence"),
        (("line of birds", "river surface", "another road"), "visual event preserved as doubled river road"),
    ),
    "surface_tension": ("cloth", "fabric", "fruit", "heavy", "weight", "shadow", "sink"),
    "intentional_large_surface": ("large", "huge", "wide", "broad surface", "cloth", "fabric"),
    "explicit_surface": (
        "background", "ground color", "full canvas", "fill the canvas", "night sky", "darkness", "dark field",
    ),
    "sunset_sky": ("sunset sky", "dusk sky"),
    "dawn": ("dawn", "daybreak", "sunrise"),
    "night": ("night",),
    # Moved out of coerce/compose.py, one system per judgement, so the words
    # coerce reacts to can be read in one place (ledger I-115). The matching
    # expression at each site is unchanged: only the literal moved.
    "variation_slow_wave": ("slow",),
    "variation_fine_tremble": ("trembling",),
    "variation_blurred_edge": ("blurring",),
    "neon_blur_scene": ("night", "glass", "neon"),
    "neon_blur_evidence": ("blur", "tear"),
    "temporal_chain_sequence": ("in order", "again and again", "at once"),
    "temporal_chain_action": ("whistle", "moving", "moved", "crossed", "dog", "flock", "cat", "laundry", "window"),
    "temporal_chain_before_after": ("before", "after"),
    "temporal_chain_reaction": ("looked up", "at once", "dog moved", "flock moved", "moving the"),
    "crescent_scene": ("crescent",),
    "polychrome_request": ("colorful", "multi-color"),
    "withered_grass_green": ("withered grass", "dry grass"),
    "autumn_forest_scene": ("forest",),
    "presence_center_upper_right": ("upper right",),
    "presence_center_upper_left": ("upper left",),
    "presence_center_lower_right": ("lower right",),
    "presence_center_lower_left": ("lower left",),
    "presence_center_right_half": ("right half",),
    "presence_center_left_half": ("left half",),
    "presence_intensity_high": ("strong", "pressure", "dense"),
    "clause_names_a_mark": (
        "line", "dot", "circle", "ellipse", "square", "triangle", "polygon", "arc", "scatter", "fill",
        "membrane", "haze", "fog", "mist", "trace", "reflection", "fade", "fading", "blur", "light", "sunlight",
        "scent", "fragrance", "bud", "bloom", "sense", "warm",
    ),
    "clause_shape_cloudform": ("cloudform",),
    "clause_shape_ellipse": ("ellipse", "oval"),
    "clause_shape_circle": ("dot", "point", "circle"),
    "small_mark_size": ("tiny", "small", "little", "thin"),
    "small_mark_kind": ("dot", "point", "circle", "ellipse", "oval"),
    "radius_clause": ("radius",),
    "clause_reflection": ("reflection", "reflected"),
    "clause_fading": ("fade", "fading", "vanish", "dissolve"),
    "sensory_kind_light": ("light", "sunlight", "soft"),
    "sensory_kind_scent": ("scent", "fragrance"),
    "sensory_kind_bud": ("bud", "bloom"),
    "sensory_kind_sense": ("sense", "presence", "arrival"),
    "line_at_right_edge": ("right edge",),
    "line_is_vertical": ("vertical line",),
    "line_is_horizontal": ("horizontal line",),
    "polygon_is_hexagonal": ("hex", "mineral"),
    "fallback_place_right_half": ("right half",),
    "fallback_place_upper_right": ("upper right",),
    "fallback_place_upper_edge": ("upper edge", "top edge"),
    "fallback_arrangement_scatter": ("scatter",),
    "fallback_arrangement_line_up": ("line up",),
    "grid_requests_square": ("square", "squares", "brick", "bricks"),
    "grid_requests_line": ("line", "stroke"),
}


def expand_intermediate(
    ddl: str,
    context_text: str | None = None,
    composition_seed: int | None = None,
    *,
    plugin_instructions_present: bool = False,
    focus: str | None = None,
    variation_amplitude: str | None = None,
    variation_seed: int | None = None,
    variation_report: dict | None = None,
) -> str:
    return expand_intermediate_ddl(
        ddl,
        lang="en",
        context_text=context_text,
        composition_seed=composition_seed,
        plugin_instructions_present=plugin_instructions_present,
        focus=focus,
        variation_amplitude=variation_amplitude,
        variation_seed=variation_seed,
        variation_report=variation_report,
    )


SUPPORT = InstructionLanguageSupport(
    code="en",
    stage1_prompt=STAGE1_PROMPT,
    stage2_prompt=STAGE2_PROMPT,
    expand_intermediate=expand_intermediate,
    coerce_markers=COERCE_MARKERS,
)
