"""Verified model metadata seeded from no-git-sync/api-test/model-config.md."""

MODEL_CONFIG_VERSION = "1.1.0"
MODEL_CONFIG_LAST_UPDATED = "2026-07-17T07:32:00Z"

VERIFIED_NVIDIA_MODELS: list[dict[str, object]] = [
    {"id":"google/gemma-4-31b-it","label":"Google Gemma 4 31B Instruct","purposes":["llm","vision"],"recommendation_level":5,"speed_class":"fast","speed_label":"高速 (約15〜22秒)","comment_ja":"本アプリの表現思想（余白・焦点の構成）に最適化されたDDLを出力。Visionでの芸術的読解・文脈理解も最高峰です。本命モデル。","comment_en":"Best adapted to the app's artistic core (negative space and focus). Outstanding Vision comprehension."},
    {"id":"mistralai/mistral-medium-3.5-128b","label":"mistralai/mistral-medium-3.5-128b","purposes":["llm","vision"],"recommendation_level":5,"speed_class":"fast","speed_label":"高速 (約17〜53秒)","comment_ja":"図形の「揺らぎ」パラメータを仕様通り正確に適用し、視認性の高い美しい配色を安定出力する非常に好適なモデル。","comment_en":"Accurately applies variation parameters and stably outputs high-contrast, beautiful color scores."},
    {"id":"mistralai/mistral-small-4-119b-2603","label":"mistralai/mistral-small-4-119b-2603","purposes":["llm","vision"],"recommendation_level":5,"speed_class":"ultra-fast","speed_label":"超高速 (約4〜5秒)","comment_ja":"LLM/Visionともに脅威の5秒前後で処理。シンプルで過密化のないソリッドな楽譜を極めてスムーズに構築します。","comment_en":"Blazing fast response times around 5 seconds. Generates clean and solid scores without overcrowding."},
    {"id":"qwen/qwen3.5-122b-a10b","label":"qwen/qwen3.5-122b-a10b","purposes":["llm","vision"],"recommendation_level":4,"speed_class":"slow","speed_label":"低速 (約109〜118秒)","comment_ja":"応答は遅いですが、元の指示のコンテキストをカラーヒントに色濃く反映し、Visionでの哲学的な分析能力も優秀です。","comment_en":"Preserves context accurately in color_hint. Excellent philosophical Vision analysis."},
    {"id":"meta/llama-3.2-11b-vision-instruct","label":"meta/llama-3.2-11b-vision-instruct","purposes":["vision"],"recommendation_level":4,"speed_class":"fast","speed_label":"高速 (約13秒)","comment_ja":"応答が軽く、画像内テキストと幾何学的形状の関係性を正確に捉えます。専用の画像評価モデルとして非常に適しています。","comment_en":"Lightweight and fast. Highly capable of extracting relations between text and geometry in patterns."},
    {"id":"meta/llama-3.1-70b-instruct","label":"meta/llama-3.1-70b-instruct","purposes":["llm"],"recommendation_level":4,"speed_class":"medium","speed_label":"中速 (約119秒)","comment_ja":"指示文の細かなニュアンスを、背景色の選定や線の密度へと高次元に抽象化できる実力派モデル。","comment_en":"Highly capable of abstracting subtle text nuances into color palettes and line densities."},
    {"id":"meta/llama-3.2-90b-vision-instruct","label":"Llama 3.2 90B Vision Instruct","purposes":["vision"],"recommendation_level":4,"speed_class":"medium","speed_label":"中速 (約52秒)","comment_ja":"大容量モデルならではの安定感があり、幾何学的パターンの組み合わせを論理的・詳細に解説します。","comment_en":"Highly stable output, describing geometric pattern variations with logical consistency."},
    {"id":"mistralai/mistral-nemotron","label":"mistralai/mistral-nemotron","purposes":["llm"],"recommendation_level":4,"speed_class":"ultra-fast","speed_label":"超高速 (約8秒)","comment_ja":"高速応答。3つの描画命令で円と放射状の線を生成し、レイアウトやマージンに破綻がないScoreを出力。","comment_en":"Fast and lightweight. Stably outputs simple 3-instruction scores with radial layout alignment."},
    {"id":"nvidia/llama-3.3-nemotron-super-49b-v1","label":"nvidia/llama-3.3-nemotron-super-49b-v1","purposes":["llm"],"recommendation_level":4,"speed_class":"fast","speed_label":"高速 (約19秒)","comment_ja":"レイアウト指示やPerlinノイズ等のバリエーションを、本アプリの仕様通りに最も忠実に反映できるモデルの一つ。","comment_en":"Highly compliant with layout rules and variation specs such as Perlin noise."},
    {"id":"google/gemma-3n-e4b-it","label":"google/gemma-3n-e4b-it","purposes":["vision"],"recommendation_level":3,"speed_class":"fast","speed_label":"高速 (約21秒)","comment_ja":"画像内の「楕円形」「モノトーン調」など、複数の作品の共通要素を的確に整理して出力する能力があります。","comment_en":"Capable of listing visual elements like ellipses and monochromatic structures from contact sheets."},
    {"id":"google/gemma-3n-e2b-it","label":"google/gemma-3n-e2b-it","purposes":["vision"],"recommendation_level":3,"speed_class":"fast","speed_label":"高速 (約17秒)","comment_ja":"幾何学パターン、シンプルな色調、配置の動きなど視覚的特徴をしっかりと抽出して出力可能。","comment_en":"Extracts basic geometric visual components, simple colors, and motions from output sheets."},
    {"id":"meta/llama-3.1-8b-instruct","label":"meta/llama-3.1-8b-instruct","purposes":["llm"],"recommendation_level":3,"speed_class":"ultra-fast","speed_label":"超高速 (約4.6秒)","comment_ja":"レスポンスは最速クラスですが、やや具体例（Few-shot）に引きずられた定型的な構図になりやすい傾向があります。","comment_en":"Blazing fast, but tends to output generic compositions heavily influenced by few-shot templates."},
    {"id":"meta/llama-3.2-3b-instruct","label":"meta/llama-3.2-3b-instruct","purposes":["llm"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"低速 (約121秒)","comment_ja":"応答が遅れる傾向にありますが、太陽の円形を画面全体に置き、重心を動かすなど独自の構図解釈力を持っています。","comment_en":"Prone to high latency, but demonstrates unique layout logic (e.g. dynamic off-center focal placement)."},
    {"id":"meta/llama-3.3-70b-instruct","label":"Meta Llama 3.3 70B Instruct","purposes":["llm"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"低速 (約191秒)","comment_ja":"LLM出力自体の品質は高いですが、応答が重く、Vision APIテスト時に長大なタイムアウト（15分超）を引き起こす特性があります。","comment_en":"High quality LLM output, but slow response times and prone to extreme API timeouts on Vision."},
    {"id":"meta/llama-3.2-1b-instruct","label":"meta/llama-3.2-1b-instruct","purposes":["llm"],"recommendation_level":2,"speed_class":"low-speed-outlier","speed_label":"低速 (約126秒)","comment_ja":"LLM検証はパスするものの、DDLの指示が「太陽が昇る」程度に縮退しやすく、構図決定能力は弱めです。","comment_en":"Stably formatted but tends to oversimplify DDL syntax, yielding weak compositions."},
    {"id":"meta/llama-4-maverick-17b-128e-instruct","label":"meta/llama-4-maverick-17b-128e-instruct","purposes":["llm"],"recommendation_level":2,"speed_class":"low-speed-outlier","speed_label":"極低速 (約240秒)","comment_ja":"解釈自体は可能ですが、LLMの接続・応答に極めて長い時間（4分）を要するため、実用向きではありません。","comment_en":"Yields correct outputs but causes heavy UI latency (around 4 minutes)."},
    {"id":"mistralai/ministral-14b-instruct-2512","label":"mistralai/ministral-14b-instruct-2512","purposes":["llm"],"recommendation_level":2,"speed_class":"low-speed-outlier","speed_label":"極低速 (約240秒)","comment_ja":"処理速度が著しく遅く、Vision検証時にも18分超の長大なハングを引き起こしたため、推奨されません。","comment_en":"Extremely slow response times and prone to severe API blocks on Vision."},
    {"id":"mistralai/mistral-large-3-675b-instruct-2512","label":"mistralai/mistral-large-3-675b-instruct-2512","purposes":["llm"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"極低速 (約240秒)","comment_ja":"675Bの超大型モデル。応答は極めて遅いですが、LLMでのDDL解釈・構造化のポテンシャルは非常に高いです。","comment_en":"Ultra large 675B model. Latency is high, but the potential of LLM output quality is prominent."},
    {"id":"mistralai/mixtral-8x7b-instruct-v0.1","label":"mistralai/mixtral-8x7b-instruct-v0.1","purposes":["llm"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"低速 (約178秒)","comment_ja":"定番のMoEモデル。LLM構造化は問題ありませんが、NIM上の接続遅延が目立ちます。","comment_en":"Reliable MoE model, but suffers from significant NIM connection latency."},
    {"id":"nvidia/llama-3.1-nemotron-nano-8b-v1","label":"nvidia/llama-3.1-nemotron-nano-8b-v1","purposes":["llm"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"低速 (約123秒)","comment_ja":"Nemotronの軽量調整版。LLM側のスキーマ準拠はOKですが、少々時間がかかります。","comment_en":"Nano Nemotron model. Schema compliance is good but latency is somewhat high."},
    {"id":"nvidia/llama-3.3-nemotron-super-49b-v1.5","label":"nvidia/llama-3.3-nemotron-super-49b-v1.5","purposes":["llm"],"recommendation_level":2,"speed_class":"low-speed-outlier","speed_label":"極低速 (約250秒)","comment_ja":"検証は通るものの応答が非常に遅く、4分以上の遅延が生じるため他モデルの利用を推奨します。","comment_en":"Verified as OK but latency is excessive (over 4 minutes), not recommended."},
    {"id":"nvidia/nvidia-nemotron-nano-9b-v2","label":"nvidia/nvidia-nemotron-nano-9b-v2","purposes":["llm"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"低速 (約115秒)","comment_ja":"9Bの小型モデル。DDL解釈は定型になりがちですが、安定してJSON出力を落とし込めます。","comment_en":"Small 9B model. DDL style tends to be templated but structures correctly."},
    {"id":"poolside/laguna-xs-2.1","label":"poolside/laguna-xs-2.1","purposes":["llm"],"recommendation_level":3,"speed_class":"ultra-fast","speed_label":"超高速 (約3.8秒)","comment_ja":"約3.8秒という脅威的な高速性。ただし、構造化時にやや過剰なパラメータ（ノイズ定義等）を付与する傾向があります。","comment_en":"Extremely fast (3.8s) but tends to generate slightly unstable layout structures."},
    {"id":"bytedance/seed-oss-36b-instruct","label":"bytedance/seed-oss-36b-instruct","purposes":["llm"],"recommendation_level":2,"speed_class":"low-speed-outlier","speed_label":"極低速 (約240秒)","comment_ja":"応答生成が極めて遅く、実運用でのUI上のフラストレーションが大きいため推奨されません。","comment_en":"Operates successfully but response generation is extremely slow, not suitable for production."},
    {"id":"stepfun-ai/step-3.5-flash","label":"stepfun-ai/step-3.5-flash","purposes":["llm"],"recommendation_level":3,"speed_class":"fast","speed_label":"高速 (約12秒)","comment_ja":"12秒の高速応答。シンプルなScoreを問題なく出力できる実力があります。","comment_en":"Fast response in 12s. Capable of outputting simple scores without errors."},
    {"id":"z-ai/glm-5.2","label":"z-ai/glm-5.2","purposes":["llm","vision"],"recommendation_level":3,"speed_class":"low-speed-outlier","speed_label":"極低速 (約107〜240秒)","comment_ja":"描画指示の構造化は極めて正確ですが、LLM/Visionともに処理時間が非常に長いため補助的な利用に留まります。","comment_en":"Highly accurate layout structuring, but suffers from severe latency."},
    {"id":"nvidia/nemotron-nano-12b-v2-vl","label":"nvidia/nemotron-nano-12b-v2-vl","purposes":["vision"],"recommendation_level":2,"speed_class":"ultra-fast","speed_label":"超高速 (約4秒)","comment_ja":"応答は非常に高速ですが、画像内の簡単な文字認識（OCR）的な回答に留まり、詳細な芸術性評価には至りません。","comment_en":"Fast response, but limited to low-level text recognition (OCR) and lacks deep visual/artistic analysis."},
    {"id":"nvidia/llama-3.1-nemotron-nano-vl-8b-v1","label":"nvidia/llama-3.1-nemotron-nano-vl-8b-v1","purposes":["vision"],"recommendation_level":2,"speed_class":"ultra-fast","speed_label":"超高速 (約2.9秒)","comment_ja":"応答は2.9秒と最速。今回は「正しい、」という極小の回答のみで、実質的な画像解析文にはなりませんでした。","comment_en":"Fastest response time but only outputs brief words, not capable of complex visual analysis."},
    {"id":"stepfun-ai/step-3.7-flash","label":"stepfun-ai/step-3.7-flash","purposes":["vision"],"recommendation_level":2,"speed_class":"ultra-fast","speed_label":"超高速 (約6.1秒)","comment_ja":"Vision接続はOKですが、返答内容がほぼ空で返るケースがあり、詳細なフィードバックには不安定です。","comment_en":"Vision API connection works but tends to return empty or minimal responses."},
]
