"""Verified model metadata measured against NVIDIA NIM on 2026-07-20 and 2026-07-21.

Three benchmark runs (midday, evening and late night, three LLM attempts plus
one Vision attempt each) replaced the earlier single-run estimates.
Recommendations are split by purpose because the two are judged differently:
LLM use on whether a model succeeds every attempt without breaking the score
schema and with few corrections, Vision use on how much of a known image it
actually reports.

Speed labels name every run. NIM latency for the same model swung between 221s
and 114s on one day, so a single number would misrepresent it.

`eol` marks a model the provider has retired. Retired models stay listed so an
artwork that names one still shows a meaningful label, but they cannot be
selected for a new drawing. Models an artwork names are kept listed even when
they scored badly or could not be measured, for the same reason.

Method and rubric: no-git-sync/fable5/mode-api-claude/SCORING-DESIGN.md
"""

MODEL_CONFIG_VERSION = "2.1.0"
MODEL_CONFIG_LAST_UPDATED = "2026-07-20T22:41:00Z"

VERIFIED_NVIDIA_MODELS: list[dict[str, object]] = [
    {"id": "mistralai/mistral-nemotron", "label": "mistralai/mistral-nemotron", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "ultra-fast", "speed_label": "昼 121s / 夕 10s / 深夜 8s", "comment_ja": "実測 9/9 成功。スキーマ違反なし。補正発火 平均 5.0。応答中央値 昼 121s / 夕 10s / 深夜 8s。", "comment_en": "9 of 9 attempts succeeded; no schema violations; 5.0 corrections on average; median response midday 121s / evening 10s / late night 8s."},
    {"id": "meta/llama-3.1-70b-instruct", "label": "meta/llama-3.1-70b-instruct", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "fast", "speed_label": "昼 52s / 夕 29s / 深夜 64s", "comment_ja": "実測 9/9 成功。スキーマ違反なし。補正発火 平均 5.8。応答中央値 昼 52s / 夕 29s / 深夜 64s。", "comment_en": "9 of 9 attempts succeeded; no schema violations; 5.8 corrections on average; median response midday 52s / evening 29s / late night 64s."},
    {"id": "meta/llama-3.2-3b-instruct", "label": "meta/llama-3.2-3b-instruct", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "fast", "speed_label": "昼 121s / 夕 13s / 深夜 121s", "comment_ja": "実測 9/9 成功。スキーマ違反なし。補正発火 平均 5.9。応答中央値 昼 121s / 夕 13s / 深夜 121s。", "comment_en": "9 of 9 attempts succeeded; no schema violations; 5.9 corrections on average; median response midday 121s / evening 13s / late night 121s."},
    {"id": "qwen/qwen3-next-80b-a3b-instruct", "label": "qwen/qwen3-next-80b-a3b-instruct", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "ultra-fast", "speed_label": "昼 7s / 夕 7s / 深夜 8s", "comment_ja": "実測 9/9 成功。スキーマ違反なし。補正発火 平均 6.0。応答中央値 昼 7s / 夕 7s / 深夜 8s。", "comment_en": "9 of 9 attempts succeeded; no schema violations; 6.0 corrections on average; median response midday 7s / evening 7s / late night 8s."},
    {"id": "poolside/laguna-xs-2.1", "label": "poolside/laguna-xs-2.1", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "ultra-fast", "speed_label": "昼 4s / 夕 4s / 深夜 4s", "comment_ja": "実測 9/9 成功。スキーマ違反なし。補正発火 平均 7.2。応答中央値 昼 4s / 夕 4s / 深夜 4s。", "comment_en": "9 of 9 attempts succeeded; no schema violations; 7.2 corrections on average; median response midday 4s / evening 4s / late night 4s."},
    {"id": "nvidia/ising-calibration-1-35b-a3b", "label": "nvidia/ising-calibration-1-35b-a3b", "purposes": ["llm"], "recommendation_llm": 3, "speed_class": "fast", "speed_label": "昼 12s / 夕 22s / 深夜 13s", "comment_ja": "実測 9/9 成功。スキーマ違反なし。補正発火 平均 14.4。応答中央値 昼 12s / 夕 22s / 深夜 13s。", "comment_en": "9 of 9 attempts succeeded; no schema violations; 14.4 corrections on average; median response midday 12s / evening 22s / late night 13s."},
    {"id": "nvidia/llama-3.3-nemotron-super-49b-v1", "label": "nvidia/llama-3.3-nemotron-super-49b-v1", "purposes": ["llm"], "recommendation_llm": 5, "speed_class": "fast", "speed_label": "昼 24s / 夕 57s / 深夜 44s", "comment_ja": "実測 8/8 成功。スキーマ違反なし。補正発火 平均 4.6。混雑時の Stage 1 無応答 1 回。応答中央値 昼 24s / 夕 57s / 深夜 44s。", "comment_en": "8 of 8 attempts succeeded; no schema violations; 4.6 corrections on average; Stage 1 silent once under load; median response midday 24s / evening 57s / late night 44s."},
    {"id": "nvidia/nemotron-nano-12b-v2-vl", "label": "nvidia/nemotron-nano-12b-v2-vl", "purposes": ["llm", "vision"], "recommendation_llm": 3, "recommendation_vision": 4, "speed_class": "fast", "speed_label": "昼 19s / 夕 29s / 深夜 16s", "comment_ja": "実測 8/8 成功。スキーマ違反なし。補正発火 平均 8.4。応答中央値 昼 19s / 夕 29s / 深夜 16s。Vision 再現率 0.89。", "comment_en": "8 of 8 attempts succeeded; no schema violations; 8.4 corrections on average; median response midday 19s / evening 29s / late night 16s; Vision recall 0.89."},
    {"id": "google/gemma-4-31b-it", "label": "Google Gemma 4 31B Instruct", "purposes": ["llm", "vision"], "recommendation_llm": 4, "recommendation_vision": 5, "speed_class": "medium", "speed_label": "昼 221s / 夕 114s / 深夜 199s", "comment_ja": "実測 7/7 成功。スキーマ違反なし。補正発火 平均 5.9。混雑時の Stage 1 無応答 1 回。応答中央値 昼 221s / 夕 114s / 深夜 199s。Vision 再現率 1.00。", "comment_en": "7 of 7 attempts succeeded; no schema violations; 5.9 corrections on average; Stage 1 silent once under load; median response midday 221s / evening 114s / late night 199s; Vision recall 1.00."},
    {"id": "meta/llama-3.3-70b-instruct", "label": "Meta Llama 3.3 70B Instruct", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "slow", "speed_label": "昼 174s / 夕 149s / 深夜 180s", "comment_ja": "実測 6/6 成功。スキーマ違反なし。補正発火 平均 6.7。混雑時の Stage 1 無応答 2 回。応答中央値 昼 174s / 夕 149s / 深夜 180s。", "comment_en": "6 of 6 attempts succeeded; no schema violations; 6.7 corrections on average; Stage 1 silent 2 times under load; median response midday 174s / evening 149s / late night 180s."},
    {"id": "mistralai/mistral-large-3-675b-instruct-2512", "label": "mistralai/mistral-large-3-675b-instruct-2512", "purposes": ["llm"], "recommendation_llm": 3, "speed_class": "slow", "speed_label": "昼 165s / 夕 156s / 深夜 158s", "comment_ja": "実測 6/6 成功。スキーマ違反なし。補正発火 平均 8.0。混雑時の Stage 1 無応答 3 回。応答中央値 昼 165s / 夕 156s / 深夜 158s。", "comment_en": "6 of 6 attempts succeeded; no schema violations; 8.0 corrections on average; Stage 1 silent 3 times under load; median response midday 165s / evening 156s / late night 158s."},
    {"id": "qwen/qwen3.5-397b-a17b", "label": "qwen/qwen3.5-397b-a17b", "purposes": ["llm"], "recommendation_llm": 5, "speed_class": "slow", "speed_label": "昼 190s / 深夜 162s", "comment_ja": "実測 5/5 成功。スキーマ違反なし。補正発火 平均 3.8。混雑時の Stage 1 無応答 4 回。応答中央値 昼 190s / 深夜 162s。", "comment_en": "5 of 5 attempts succeeded; no schema violations; 3.8 corrections on average; Stage 1 silent 4 times under load; median response midday 190s / late night 162s."},
    {"id": "z-ai/glm-5.2", "label": "z-ai/glm-5.2", "purposes": ["llm"], "recommendation_llm": 5, "speed_class": "medium", "speed_label": "夕 148s / 深夜 110s", "comment_ja": "実測 5/5 成功。スキーマ違反なし。補正発火 平均 4.2。混雑時の Stage 1 無応答 1 回。応答中央値 夕 148s / 深夜 110s。", "comment_en": "5 of 5 attempts succeeded; no schema violations; 4.2 corrections on average; Stage 1 silent once under load; median response evening 148s / late night 110s."},
    {"id": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", "label": "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning", "purposes": ["llm", "vision"], "recommendation_llm": 3, "recommendation_vision": 4, "speed_class": "medium", "speed_label": "昼 119s / 夕 70s / 深夜 153s", "comment_ja": "実測 4/4 成功。スキーマ違反なし。補正発火 平均 7.8。応答中央値 昼 119s / 夕 70s / 深夜 153s。Vision 再現率 0.89。", "comment_en": "4 of 4 attempts succeeded; no schema violations; 7.8 corrections on average; median response midday 119s / evening 70s / late night 153s; Vision recall 0.89."},
    {"id": "deepseek-ai/deepseek-v4-flash", "label": "deepseek-ai/deepseek-v4-flash", "purposes": ["llm"], "recommendation_llm": 3, "speed_class": "fast", "speed_label": "昼 16s / 深夜 101s", "comment_ja": "実測 3/3 成功。スキーマ違反なし。補正発火 平均 9.3。応答中央値 昼 16s / 深夜 101s。", "comment_en": "3 of 3 attempts succeeded; no schema violations; 9.3 corrections on average; median response midday 16s / late night 101s."},
    {"id": "openai/gpt-oss-120b", "label": "openai/gpt-oss-120b", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "ultra-fast", "speed_label": "昼 13s / 夕 10s / 深夜 11s", "comment_ja": "実測 6/7 成功。スキーマ違反 1 回。補正発火 平均 3.5。混雑時の Stage 1 無応答 2 回。応答中央値 昼 13s / 夕 10s / 深夜 11s。", "comment_en": "6 of 7 attempts succeeded; 1 score schema violations; 3.5 corrections on average; Stage 1 silent 2 times under load; median response midday 13s / evening 10s / late night 11s."},
    {"id": "nvidia/llama-3.3-nemotron-super-49b-v1.5", "label": "nvidia/llama-3.3-nemotron-super-49b-v1.5", "purposes": ["llm"], "recommendation_llm": 4, "speed_class": "slow", "speed_label": "昼 136s", "comment_ja": "実測 1/1 成功。スキーマ違反なし。補正発火 平均 1.0。混雑時の Stage 1 無応答 1 回。応答中央値 昼 136s。", "comment_en": "1 of 1 attempts succeeded; no schema violations; 1.0 corrections on average; Stage 1 silent once under load; median response midday 136s."},
    {"id": "minimaxai/minimax-m3", "label": "minimaxai/minimax-m3", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "medium", "speed_label": "昼 132s / 夕 53s", "comment_ja": "実測 6/9 成功。tool calling の引数不正 3 回。補正発火 平均 6.3。応答中央値 昼 132s / 夕 53s。", "comment_en": "6 of 9 attempts succeeded; 3 malformed tool calls; 6.3 corrections on average; median response midday 132s / evening 53s."},
    {"id": "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", "label": "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", "purposes": ["llm", "vision"], "recommendation_llm": 2, "recommendation_vision": 3, "speed_class": "slow", "speed_label": "昼 122s / 夕 122s / 深夜 122s", "comment_ja": "実測 6/9 成功。スキーマ違反 3 回。補正発火 平均 6.3。応答中央値 昼 122s / 夕 122s / 深夜 122s。Vision 再現率 0.67。", "comment_en": "6 of 9 attempts succeeded; 3 score schema violations; 6.3 corrections on average; median response midday 122s / evening 122s / late night 122s; Vision recall 0.67."},
    {"id": "deepseek-ai/deepseek-v4-pro", "label": "deepseek-ai/deepseek-v4-pro", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "fast", "speed_label": "昼 16s / 夕 28s", "comment_ja": "実測 6/9 成功。tool calling の引数不正 3 回。補正発火 平均 7.8。応答中央値 昼 16s / 夕 28s。", "comment_en": "6 of 9 attempts succeeded; 3 malformed tool calls; 7.8 corrections on average; median response midday 16s / evening 28s."},
    {"id": "minimaxai/minimax-m2.7", "label": "minimaxai/minimax-m2.7", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "fast", "speed_label": "昼 22s / 夕 74s / 深夜 33s", "comment_ja": "実測 6/9 成功。スキーマ違反 3 回。補正発火 平均 8.5。応答中央値 昼 22s / 夕 74s / 深夜 33s。", "comment_en": "6 of 9 attempts succeeded; 3 score schema violations; 8.5 corrections on average; median response midday 22s / evening 74s / late night 33s."},
    {"id": "nvidia/nemotron-3-super-120b-a12b", "label": "nvidia/nemotron-3-super-120b-a12b", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "fast", "speed_label": "昼 21s / 夕 35s / 深夜 23s", "comment_ja": "実測 5/9 成功。スキーマ違反 4 回。補正発火 平均 10.4。応答中央値 昼 21s / 夕 35s / 深夜 23s。", "comment_en": "5 of 9 attempts succeeded; 4 score schema violations; 10.4 corrections on average; median response midday 21s / evening 35s / late night 23s."},
    {"id": "bytedance/seed-oss-36b-instruct", "label": "bytedance/seed-oss-36b-instruct", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "medium", "speed_label": "昼 95s", "comment_ja": "実測 1/2 成功。tool calling の引数不正 1 回。補正発火 平均 10.0。混雑時の Stage 1 無応答 5 回。応答中央値 昼 95s。", "comment_en": "1 of 2 attempts succeeded; 1 malformed tool calls; 10.0 corrections on average; Stage 1 silent 5 times under load; median response midday 95s."},
    {"id": "nvidia/nvidia-nemotron-nano-9b-v2", "label": "nvidia/nvidia-nemotron-nano-9b-v2", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "fast", "speed_label": "昼 73s / 深夜 40s", "comment_ja": "実測 2/4 成功。tool calling の引数不正 2 回。補正発火 平均 2.5。応答中央値 昼 73s / 深夜 40s。", "comment_en": "2 of 4 attempts succeeded; 2 malformed tool calls; 2.5 corrections on average; median response midday 73s / late night 40s."},
    {"id": "meta/llama-3.1-8b-instruct", "label": "meta/llama-3.1-8b-instruct", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "ultra-fast", "speed_label": "昼 3s / 夕 4s / 深夜 13s", "comment_ja": "実測 4/9 成功。スキーマ違反 5 回。補正発火 平均 3.5。応答中央値 昼 3s / 夕 4s / 深夜 13s。", "comment_en": "4 of 9 attempts succeeded; 5 score schema violations; 3.5 corrections on average; median response midday 3s / evening 4s / late night 13s."},
    {"id": "mistralai/mistral-medium-3.5-128b", "label": "mistralai/mistral-medium-3.5-128b", "purposes": ["llm", "vision"], "recommendation_llm": 2, "recommendation_vision": 4, "speed_class": "medium", "speed_label": "昼 128s / 夕 168s / 深夜 92s", "comment_ja": "実測 4/9 成功。スキーマ違反 5 回。補正発火 平均 3.8。応答中央値 昼 128s / 夕 168s / 深夜 92s。Vision 再現率 0.94。", "comment_en": "4 of 9 attempts succeeded; 5 score schema violations; 3.8 corrections on average; median response midday 128s / evening 168s / late night 92s; Vision recall 0.94."},
    {"id": "mistralai/mistral-small-4-119b-2603", "label": "mistralai/mistral-small-4-119b-2603", "purposes": ["llm", "vision"], "recommendation_llm": 2, "recommendation_vision": 4, "speed_class": "ultra-fast", "speed_label": "昼 3s / 夕 6s / 深夜 4s", "comment_ja": "実測 4/9 成功。スキーマ違反 5 回。補正発火 平均 5.5。応答中央値 昼 3s / 夕 6s / 深夜 4s。Vision 再現率 0.94。", "comment_en": "4 of 9 attempts succeeded; 5 score schema violations; 5.5 corrections on average; median response midday 3s / evening 6s / late night 4s; Vision recall 0.94."},
    {"id": "nvidia/nemotron-3-ultra-550b-a55b", "label": "nvidia/nemotron-3-ultra-550b-a55b", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "fast", "speed_label": "昼 40s / 夕 95s / 深夜 38s", "comment_ja": "実測 3/7 成功。スキーマ違反 4 回。補正発火 平均 10.3。応答中央値 昼 40s / 夕 95s / 深夜 38s。", "comment_en": "3 of 7 attempts succeeded; 4 score schema violations; 10.3 corrections on average; median response midday 40s / evening 95s / late night 38s."},
    {"id": "mistralai/mixtral-8x7b-instruct-v0.1", "label": "mistralai/mixtral-8x7b-instruct-v0.1", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "slow", "speed_label": "昼 125s / 夕 236s / 深夜 125s", "comment_ja": "実測 3/9 成功。スキーマ違反 6 回。補正発火 平均 1.0。応答中央値 昼 125s / 夕 236s / 深夜 125s。", "comment_en": "3 of 9 attempts succeeded; 6 score schema violations; 1.0 corrections on average; median response midday 125s / evening 236s / late night 125s."},
    {"id": "openai/gpt-oss-20b", "label": "openai/gpt-oss-20b", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "fast", "speed_label": "深夜 14s", "comment_ja": "実測 1/5 成功。スキーマ違反 4 回。補正発火 平均 1.0。混雑時の Stage 1 無応答 4 回。応答中央値 深夜 14s。", "comment_en": "1 of 5 attempts succeeded; 4 score schema violations; 1.0 corrections on average; Stage 1 silent 4 times under load; median response late night 14s."},
    {"id": "stepfun-ai/step-3.7-flash", "label": "stepfun-ai/step-3.7-flash", "purposes": ["llm"], "recommendation_llm": 2, "speed_class": "medium", "speed_label": "夕 43s", "comment_ja": "実測 1/6 成功。スキーマ違反 5 回。補正発火 平均 3.0。混雑時の Stage 1 無応答 3 回。応答中央値 夕 43s。", "comment_en": "1 of 6 attempts succeeded; 5 score schema violations; 3.0 corrections on average; Stage 1 silent 3 times under load; median response evening 43s."},
    {"id": "google/gemma-3n-e2b-it", "label": "google/gemma-3n-e2b-it", "purposes": ["vision"], "recommendation_vision": 4, "speed_class": "unknown", "speed_label": "Vision 12s", "comment_ja": "実測 0/9 成功。tool calling の引数不正 9 回。応答中央値 Vision 12s。Vision 再現率 0.94。", "comment_en": "0 of 9 attempts succeeded; 9 malformed tool calls; median response Vision 12s; Vision recall 0.94."},
    {"id": "google/gemma-3n-e4b-it", "label": "google/gemma-3n-e4b-it", "purposes": ["vision"], "recommendation_vision": 4, "speed_class": "unknown", "speed_label": "Vision 15s", "comment_ja": "実測 0/9 成功。tool calling の引数不正 9 回。応答中央値 Vision 15s。Vision 再現率 0.94。", "comment_en": "0 of 9 attempts succeeded; 9 malformed tool calls; median response Vision 15s; Vision recall 0.94."},
    {"id": "meta/llama-3.2-11b-vision-instruct", "label": "meta/llama-3.2-11b-vision-instruct", "purposes": ["vision"], "recommendation_vision": 4, "speed_class": "unknown", "speed_label": "Vision 9s", "comment_ja": "実測 0/9 成功。スキーマ違反 9 回。応答中央値 Vision 9s。Vision 再現率 0.94。", "comment_en": "0 of 9 attempts succeeded; 9 score schema violations; median response Vision 9s; Vision recall 0.94."},
    {"id": "nvidia/nemotron-3-nano-30b-a3b", "label": "nvidia/nemotron-3-nano-30b-a3b", "purposes": ["llm"], "recommendation_llm": 1, "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "実測 0/9 成功。スキーマ違反 9 回。", "comment_en": "0 of 9 attempts succeeded; 9 score schema violations."},
    {"id": "meta/llama-3.2-1b-instruct", "label": "meta/llama-3.2-1b-instruct", "purposes": ["llm"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "meta/llama-3.2-90b-vision-instruct", "label": "Llama 3.2 90B Vision Instruct", "purposes": ["vision"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "meta/llama-4-maverick-17b-128e-instruct", "label": "meta/llama-4-maverick-17b-128e-instruct", "purposes": ["llm"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "mistralai/ministral-14b-instruct-2512", "label": "mistralai/ministral-14b-instruct-2512", "purposes": ["llm"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "nvidia/llama-3.1-nemotron-nano-8b-v1", "label": "nvidia/llama-3.1-nemotron-nano-8b-v1", "purposes": ["llm"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "stepfun-ai/step-3.5-flash", "label": "stepfun-ai/step-3.5-flash", "purposes": ["llm"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "thinkingmachines/inkling", "label": "thinkingmachines/inkling", "purposes": ["llm"], "speed_class": "unknown", "speed_label": "未計測", "comment_ja": "提供は継続中。2026-07-20 の 2 回の計測では 9 回とも Stage 1 が 120 秒以内に応答せず、品質を測定できなかった。混雑の影響とみられる。", "comment_en": "Still offered. In both 2026-07-20 runs Stage 1 did not answer within 120 seconds, so nothing about its quality was measured. Consistent with provider load."},
    {"id": "qwen/qwen3.5-122b-a10b", "label": "qwen/qwen3.5-122b-a10b", "purposes": ["llm"], "eol": True, "eol_date": "2026-07-20", "speed_class": "unknown", "speed_label": "提供終了", "comment_ja": "提供終了。過去の作品は保存済みの Score と SVG で閲覧できるが、再描画はできない。", "comment_en": "Retired by the provider. Existing artworks still render from their stored score and SVG, but cannot be redrawn."},
    {"id": "qwen/qwen3-coder-480b-a35b-instruct", "label": "qwen/qwen3-coder-480b-a35b-instruct", "purposes": ["llm"], "eol": True, "eol_date": "2026-07-20", "speed_class": "unknown", "speed_label": "提供終了", "comment_ja": "提供終了。過去の作品は保存済みの Score と SVG で閲覧できるが、再描画はできない。", "comment_en": "Retired by the provider. Existing artworks still render from their stored score and SVG, but cannot be redrawn."},
]
