// Generated by server/scripts/gen_saijiki_kt.py from saijiki.py. Do not edit by hand.
package app.inku.mobile.pipeline

/**
 * The saijiki vocabulary, baked from the server's `saijiki.py`.
 *
 * This client has no `/api/saijiki` to hydrate from, so this snapshot is what
 * the vocabulary dialog shows. Regenerate with:
 *
 *     cd server && uv run python scripts/gen_saijiki_kt.py
 */
object SaijikiGenerated {
    data class Category(
        val key: String,
        val nameJa: String,
        val nameEn: String,
        val wordsJa: List<String>,
        val wordsEn: List<String>,
    )

    val CATEGORIES: List<Category> = listOf(
        Category(
            key = "katachi",
            nameJa = "かたち",
            nameEn = "forms",
            wordsJa = listOf("円", "楕円", "三角", "四角", "線", "弧", "雲形"),
            wordsEn = listOf("circle", "ellipse", "triangle", "square", "line", "arc", "cloudform"),
        ),
        Category(
            key = "katamuki",
            nameJa = "かたむき",
            nameEn = "angles",
            wordsJa = listOf("水平", "垂直", "斜め", "右上がり", "右下がり", "回転"),
            wordsEn = listOf("horizontal", "vertical", "diagonal", "rising", "falling", "rotated"),
        ),
        Category(
            key = "tezawari",
            nameJa = "てざわり",
            nameEn = "touches",
            wordsJa = listOf("銀筆", "鉛筆", "ペン", "ロットリング", "クレヨン", "チョーク", "細筆", "太筆", "ビュラン", "ドライポイント", "コンピュータ"),
            wordsEn = listOf("silverpoint", "pencil", "pen", "rotring", "crayon", "chalk", "fine-brush", "thick-brush", "burin", "drypoint", "computer"),
        ),
        Category(
            key = "tsuranari",
            nameJa = "つらなり",
            nameEn = "continuity",
            wordsJa = listOf("実線", "破線", "点線", "一点鎖線"),
            wordsEn = listOf("solid", "dashed", "dotted", "dash-dot"),
        ),
        Category(
            key = "omote",
            nameJa = "おもて",
            nameEn = "surfaces",
            wordsJa = listOf("空", "塗り", "薄墨", "粒", "点", "平行線", "交差線", "にじみ", "アクアチント", "濃い", "薄い"),
            wordsEn = listOf("empty", "flat", "pale ink wash", "grain", "stipple", "hatch", "crosshatch", "bleeding", "aquatint", "dense", "faint"),
        ),
        Category(
            key = "iro",
            nameJa = "いろ",
            nameEn = "colors",
            wordsJa = listOf("白", "黒", "青", "赤", "緑", "灰", "黄", "橙", "紫"),
            wordsEn = listOf("white", "black", "blue", "red", "green", "gray", "yellow", "orange", "purple"),
        ),
        Category(
            key = "yuragi",
            nameJa = "ゆらぎ",
            nameEn = "movements",
            wordsJa = listOf("細かく", "大きく", "ゆっくり", "速く", "揺れる", "波打つ", "震える", "滲む"),
            wordsEn = listOf("fine", "large", "slowly", "quickly", "swaying", "undulating", "trembling", "blurring"),
        ),
        Category(
            key = "basho",
            nameJa = "ばしょ",
            nameEn = "places",
            wordsJa = listOf("上", "下", "中央", "左端", "右端", "上端", "下端", "中心", "隅"),
            wordsEn = listOf("top", "bottom", "center", "left-edge", "right-edge", "top-edge", "bottom-edge", "middle", "corner"),
        ),
        Category(
            key = "ugoki",
            nameJa = "うごき",
            nameEn = "motions",
            wordsJa = listOf("置く", "並べる", "引く", "散らす", "埋める", "敷き詰める"),
            wordsEn = listOf("place", "line-up", "draw", "scatter", "fill", "tile"),
        ),
        Category(
            key = "wariai",
            nameJa = "わりあい",
            nameEn = "proportions",
            wordsJa = listOf("縦長", "横長", "全幅", "半幅", "半円", "上弦", "下弦", "三日月"),
            wordsEn = listOf("tall", "wide", "full-width", "half-width", "semicircle", "waxing", "waning", "crescent"),
        ),
        Category(
            key = "aida",
            nameJa = "あいだ",
            nameEn = "relations",
            wordsJa = listOf("沿う", "触れない", "切る", "間に", "触れる"),
            wordsEn = listOf("along", "not touching", "cutting", "between", "touching"),
        ),
    )
}
