"""Generate web/src/lib/saijiki.generated.ts from the saijiki table.

The web bundle ships this snapshot as the initial vocabulary; at runtime the
web hydrates from GET /api/saijiki. A pytest identity check (test_saijiki_api.py)
fails if the checked-in file drifts from the table, so the snapshot cannot go
stale silently.

Run: cd server && uv run python scripts/gen_saijiki_ts.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_SERVER_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SERVER_SRC) not in sys.path:
    sys.path.insert(0, str(_SERVER_SRC))

from inku_server.saijiki import display_categories  # noqa: E402

_OUTPUT = Path(__file__).resolve().parents[2] / "web" / "src" / "lib" / "saijiki.generated.ts"


def _ts_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_ts() -> str:
    lines = [
        "// Generated by server/scripts/gen_saijiki_ts.py from saijiki.py. Do not edit by hand.",
        "import type { SaijikiCategory } from './saijiki';",
        "",
        "export const GENERATED_SAIJIKI: SaijikiCategory[] = [",
    ]
    for category in display_categories("ja"):
        words = ", ".join(_ts_string(str(w)) for w in category["words"])
        lines.append("\t{")
        lines.append(f"\t\tkey: {_ts_string(str(category['key']))},")
        lines.append(f"\t\tlabel: {_ts_string(str(category['name_ja']))},")
        lines.append(f"\t\ten: {_ts_string(str(category['name_en']))},")
        lines.append(f"\t\twords: [{words}]")
        lines.append("\t},")
    lines.append("];")
    return "\n".join(lines) + "\n"


def main() -> None:
    _OUTPUT.write_text(render_ts(), encoding="utf-8")
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
