"""Generate the Android saijiki snapshot from the saijiki table.

The Android client never calls the inku API -- it has no `/api/saijiki` to
hydrate from -- so unlike the web snapshot this file is the whole vocabulary the
app will ever display. It is checked in, and a pytest identity check
(test_saijiki_kt_is_current.py) fails if it drifts from the table, so the app
cannot quietly fall a version behind the way the hand-copied list did.

Both language surfaces are emitted side by side in one category list. The web
dialog shows the Japanese and English category names together in either language
and switches only the words (SaijikiInline.svelte:60-61); keeping both names on
every category lets the client make the same judgement rather than its own.

Run: cd server && uv run python scripts/gen_saijiki_kt.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_SERVER_SRC = Path(__file__).resolve().parents[1] / "src"
if str(_SERVER_SRC) not in sys.path:
    sys.path.insert(0, str(_SERVER_SRC))

from inku_server.saijiki import display_categories  # noqa: E402

_REPO_ROOT = Path(__file__).resolve().parents[2]
_OUTPUT = (
    _REPO_ROOT
    / "android/app/src/main/java/app/inku/mobile/pipeline/SaijikiGenerated.kt"
)


def _kt_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    return '"' + escaped + '"'


def _kt_list(values) -> str:
    return "listOf(" + ", ".join(_kt_string(str(v)) for v in values) + ")"


def render_kt() -> str:
    ja = display_categories("ja")
    en = display_categories("en")
    # The two calls return the categories in the same order because each saijiki
    # entry owns both surfaces; pairing them by position is the table's own
    # pairing, not an assumption about sort order.
    assert [c["key"] for c in ja] == [c["key"] for c in en]

    lines = [
        "// Generated by server/scripts/gen_saijiki_kt.py from saijiki.py. Do not edit by hand.",
        "package app.inku.mobile.pipeline",
        "",
        "/**",
        " * The saijiki vocabulary, baked from the server's `saijiki.py`.",
        " *",
        " * This client has no `/api/saijiki` to hydrate from, so this snapshot is what",
        " * the vocabulary dialog shows. Regenerate with:",
        " *",
        " *     cd server && uv run python scripts/gen_saijiki_kt.py",
        " */",
        "object SaijikiGenerated {",
        "    data class Category(",
        "        val key: String,",
        "        val nameJa: String,",
        "        val nameEn: String,",
        "        val wordsJa: List<String>,",
        "        val wordsEn: List<String>,",
        "    )",
        "",
        "    val CATEGORIES: List<Category> = listOf(",
    ]
    for cat_ja, cat_en in zip(ja, en):
        lines.append("        Category(")
        lines.append(f"            key = {_kt_string(str(cat_ja['key']))},")
        lines.append(f"            nameJa = {_kt_string(str(cat_ja['name_ja']))},")
        lines.append(f"            nameEn = {_kt_string(str(cat_ja['name_en']))},")
        lines.append(f"            wordsJa = {_kt_list(cat_ja['words'])},")
        lines.append(f"            wordsEn = {_kt_list(cat_en['words'])},")
        lines.append("        ),")
    lines.append("    )")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> None:
    _OUTPUT.write_text(render_kt(), encoding="utf-8")
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
