// Generated from the Build1162 Web source (every `<Tooltip>` and `title=` in web/src, 173 sites) and the Swift
// counterpart chosen for each. The Web column is the regex `<Tooltip\b` (with its `text=`) and `\btitle=` over
// web/src at Build1162 (7a0f0180), in file order.

/// One Web tooltip site and the Swift source that carries it, or why the single-user app has none.
struct TooltipParityEntry {
    let web: String
    let swift: String?
    let marker: String?
    let excluded: String?
    init(web: String, swift: String, marker: String) { self.web = web; self.swift = swift; self.marker = marker; self.excluded = nil }
    init(web: String, excluded: String) { self.web = web; self.swift = nil; self.marker = nil; self.excluded = excluded }
    var component: String { String(web.split(separator: ".").first ?? "") }
}

let tooltipParityTable: [TooltipParityEntry] = [
    .init(web: "+page.svelte:2733", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipDdlNew\""),
    .init(web: "+page.svelte:2784", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipSketchToggle\""),
    .init(web: "+page.svelte:2859", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipStatsToggle\""),
    .init(web: "+page.svelte:2915", swift: "Views/CreationView.swift", marker: "showTooltips ? title : \"\""),
    .init(web: "+page.svelte:3258", swift: "Views/AboutInkuView.swift", marker: "\"appInfoHintDdlSpec\""),
    .init(web: "+page.svelte:3260", swift: "Views/AboutInkuView.swift", marker: "\"appInfoHintDdlEngine\""),
    .init(web: "+page.svelte:3262", swift: "Views/AboutInkuView.swift", marker: "\"appInfoHintRenderEngine\""),
    .init(web: "+page.svelte:3264", swift: "Views/AboutInkuView.swift", marker: "\"appInfoHintBindingProtocol\""),
    .init(web: "AIRefineModal.svelte:251", swift: "Views/AuxiliaryView.swift", marker: "auxiliary.sourceIsLocked ? lockedReason : \"\""),
    .init(web: "AIRefineModal.svelte:255", swift: "Views/AuxiliaryView.swift", marker: "serverKey: \"refineCostReading\""),
    .init(web: "AIRefineModal.svelte:255", swift: "Views/AuxiliaryView.swift", marker: "? lockedReason : model.display.tooltip(\"低速"),
    .init(web: "AIRefineModal.svelte:255", swift: "Views/AuxiliaryView.swift", marker: "serverKey: \"refineCostColor\""),
    .init(web: "AIRefineModal.svelte:255", swift: "Views/AuxiliaryView.swift", marker: "serverKey: \"refineCostLayout\""),
    .init(web: "AIRefineModal.svelte:255", swift: "Views/AuxiliaryView.swift", marker: "serverKey: \"refineCostTouch\""),
    .init(web: "AppRail.svelte:81", swift: "Views/AppRailView.swift", marker: "serverKey: \"tooltipAppRailToggle\""),
    .init(web: "AppRail.svelte:94", swift: "Views/AppRailView.swift", marker: "serverKey: \"tooltipAppRailLogo\""),
    .init(web: "AppRail.svelte:108", excluded: "単一利用者アプリに利用者メニュー・プロフィールが無い"),
    .init(web: "AppRail.svelte:132", swift: "Views/AppRailView.swift", marker: "serverKey: \"uiModeLabel\""),
    .init(web: "AppRail.svelte:156", swift: "Views/AppRailView.swift", marker: "\"tooltipsHide\" : \"tooltipsShow\""),
    .init(web: "AppRail.svelte:170", swift: "Views/AppRailView.swift", marker: "serverKey: \"tooltipAppRailSettings\""),
    .init(web: "AppRail.svelte:178", swift: "Views/AppRailView.swift", marker: "serverKey: \"tooltipAppRailTheme\""),
    .init(web: "AppRail.svelte:187", swift: "Views/AppRailView.swift", marker: "serverKey: \"tooltipAppRailLang\") + \": \" + name"),
    .init(web: "AppRail.svelte:199", excluded: "開発者モードの Build 表示は Swift に無い（版は About に出る）"),
    .init(web: "AuthPanel.svelte:44", excluded: "ログイン画面（AuthPanel）は単一利用者アプリに無い"),
    .init(web: "AuthPanel.svelte:77", excluded: "ログイン画面（AuthPanel）は単一利用者アプリに無い"),
    .init(web: "CanvasArtworkWorkspace.svelte:174", swift: "Views/CreationControls.swift", marker: "FallbackCopy.interpretHint(interpret"),
    .init(web: "CanvasArtworkWorkspace.svelte:179", swift: "Views/CreationControls.swift", marker: "FallbackCopy.composeHint(compose"),
    .init(web: "CanvasArtworkWorkspace.svelte:193", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipCanvasCaption\""),
    .init(web: "CanvasArtworkWorkspace.svelte:220", swift: "Views/CreationControls.swift", marker: "starred ? \"starOn\" : \"starOff\""),
    .init(web: "CanvasArtworkWorkspace.svelte:234", swift: "Views/LibraryPresentation.swift", marker: "marked ? \"forRevisionOn\" : \"forRevisionOff\""),
    .init(web: "CanvasArtworkWorkspace.svelte:249", swift: "Views/LibraryPresentation.swift", marker: "marked ? \"shareTargetOn\" : \"shareTargetOff\""),
    .init(web: "CanvasArtworkWorkspace.svelte:278", swift: "Views/CreationControls.swift", marker: "copiedHash == hash ? \"コピーしました\" : \"クリックでfull hashをコピーします\""),
    .init(web: "CanvasArtworkWorkspace.svelte:288", swift: "Views/CreationControls.swift", marker: "serverKey: \"historyReplayTitle\""),
    .init(web: "CanvasArtworkWorkspace.svelte:302", swift: "Views/CreationControls.swift", marker: "tooltip(\"選択中作品の生成情報を表示\")"),
    .init(web: "CanvasArtworkWorkspace.svelte:319", swift: "Views/CreationControls.swift", marker: "tooltip(\"歳時記の語と説明を参照します。\", serverKey: \"tooltipSaijikiToggle\")"),
    .init(web: "CanvasArtworkWorkspace.svelte:340", swift: "Views/CreationControls.swift", marker: "serverKey: \"historyCardExport\""),
    .init(web: "CanvasArtworkWorkspace.svelte:359", swift: "Views/CreationControls.swift", marker: "serverKey: \"exportSaveFirst\""),
    .init(web: "CanvasArtworkWorkspace.svelte:368", swift: "Views/CreationControls.swift", marker: "serverKey: $0)"),
    .init(web: "CanvasArtworkWorkspace.svelte:382", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipCanvasPresentation\""),
    .init(web: "CanvasArtworkWorkspace.svelte:405", swift: "Views/ArtworkCanvas.swift", marker: "serverKey: \"tooltipCanvasZoomOut\""),
    .init(web: "CanvasArtworkWorkspace.svelte:409", swift: "Views/ArtworkCanvas.swift", marker: "serverKey: \"tooltipCanvasZoomIn\""),
    .init(web: "CanvasArtworkWorkspace.svelte:412", swift: "Views/ArtworkCanvas.swift", marker: "serverKey: \"tooltipCanvasZoomReset\""),
    .init(web: "CanvasGenerationInfo.svelte:239", swift: "Views/CreationWorkInfoView.swift", marker: "tooltip(label, serverKey: hint)"),
    .init(web: "CanvasGenerationInfo.svelte:295", swift: "Views/CreationWorkInfoView.swift", marker: "tooltipValue(code)"),
    .init(web: "CanvasPanel.svelte:688", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipCanvasTabCanvas\""),
    .init(web: "CanvasPanel.svelte:691", swift: "Views/CreationView.swift", marker: "tooltip(\"作品の派生関係を表示\")"),
    .init(web: "CanvasPanel.svelte:707", swift: "Views/CreationView.swift", marker: "title: stage1 + \" / \" + stage2"),
    .init(web: "CanvasPanel.svelte:726", swift: "Views/CreationView.swift", marker: "title: catalog"),
    .init(web: "CanvasPanel.svelte:730", swift: "Views/CreationView.swift", marker: "title: canvas"),
    .init(web: "CanvasPanel.svelte:764", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipCanvasNavLatest\""),
    .init(web: "CanvasPanel.svelte:767", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipCanvasNavNewer\""),
    .init(web: "CanvasPanel.svelte:902", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipCanvasNavOldest\""),
    .init(web: "CanvasPanel.svelte:905", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipCanvasNavOlder\""),
    .init(web: "CanvasPresentationOverlay.svelte:77", swift: "Views/ContentView.swift", marker: "serverKey: \"tooltipCanvasNavNewer\""),
    .init(web: "CanvasPresentationOverlay.svelte:82", swift: "Views/ContentView.swift", marker: "serverKey: \"tooltipCanvasNavLatest\""),
    .init(web: "CanvasPresentationOverlay.svelte:85", swift: "Views/ContentView.swift", marker: "serverKey: \"tooltipCanvasNavOlder\""),
    .init(web: "CanvasPresentationOverlay.svelte:91", swift: "Views/ContentView.swift", marker: "starred ? \"starOn\" : \"starOff\""),
    .init(web: "CanvasPresentationOverlay.svelte:103", swift: "Views/ContentView.swift", marker: "serverKey: \"canvasCaptionToggle\""),
    .init(web: "CanvasPresentationOverlay.svelte:127", swift: "Views/ContentView.swift", marker: "serverKey: \"canvasPresentationClose\""),
    .init(web: "DatabaseAdministrationSettings.svelte:146", swift: "Views/SettingsView.swift", marker: "serverKey: \"settingsDbBackupEstimatedDiskHint\""),
    .init(web: "DdlEditor.svelte:141", swift: "Views/DdlEditorPane.swift", marker: "serverKey: \"tooltipDdlLang\""),
    .init(web: "DdlViewer.svelte:38", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipDdlLang\""),
    .init(web: "DdlViewer.svelte:46", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipDdlEdit\""),
    .init(web: "DdlViewer.svelte:54", swift: "Views/CreationControls.swift", marker: "serverKey: \"tooltipDdlPaint\""),
    .init(web: "HistoryDescription.svelte:25", swift: "Views/LibraryPresentation.swift", marker: "\"historyDescriptionCollapseTitle\" : \"historyDescriptionExpandTitle\""),
    .init(web: "HistoryManager.svelte:744", excluded: "他の利用者の作品（共有）は単一利用者アプリに無い"),
    .init(web: "HistoryManager.svelte:745", excluded: "利用者・グループへの個別共有は単一利用者アプリに無い"),
    .init(web: "HistoryManager.svelte:746", excluded: "グループ共有は単一利用者アプリに無い"),
    .init(web: "HistoryManager.svelte:758", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryThumbsTab\""),
    .init(web: "HistoryManager.svelte:761", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryListTab\""),
    .init(web: "HistoryManager.svelte:769", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryChronological\""),
    .init(web: "HistoryManager.svelte:772", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryLineageGrouped\""),
    .init(web: "HistoryManager.svelte:793", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryLatestPage\""),
    .init(web: "HistoryManager.svelte:796", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryNewerPage\""),
    .init(web: "HistoryManager.svelte:800", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryOlderPage\""),
    .init(web: "HistoryManager.svelte:803", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryOldestPage\""),
    .init(web: "HistoryManager.svelte:807", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryLatestPage\""),
    .init(web: "HistoryManager.svelte:810", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryNewerPage\""),
    .init(web: "HistoryManager.svelte:814", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryOlderPage\""),
    .init(web: "HistoryManager.svelte:817", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryOldestPage\""),
    .init(web: "HistoryManager.svelte:822", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyLibraryReturn\""),
    .init(web: "HistoryManager.svelte:829", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistorySelectAll\""),
    .init(web: "HistoryManager.svelte:834", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryStarredOnly\""),
    .init(web: "HistoryManager.svelte:842", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryForRevisionOnly\""),
    .init(web: "HistoryManager.svelte:850", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryForShareOnly\""),
    .init(web: "HistoryManager.svelte:859", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryTrashView\""),
    .init(web: "HistoryManager.svelte:867", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryMoveToTrash\""),
    .init(web: "HistoryManager.svelte:880", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryRestoreSelected\""),
    .init(web: "HistoryManager.svelte:883", swift: "Views/LibraryView.swift", marker: "serverKey: \"tooltipHistoryPermanentDelete\""),
    .init(web: "HistoryManager.svelte:921", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPreviewOpenHint\""),
    .init(web: "HistoryManager.svelte:975", swift: "Views/LibraryView.swift", marker: "library.copiedHash == hash ? model.display.tooltip(\"コピーしました\", serverKey: \"historyHashCopied\")"),
    .init(web: "HistoryManager.svelte:1028", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPreviewTitle\""),
    .init(web: "HistoryManager.svelte:1040", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyLineageExpandTitle\""),
    .init(web: "HistoryManager.svelte:1046", swift: "Views/LibraryView.swift", marker: "serverKey: \"historySelectLineageTitle\""),
    .init(web: "HistoryManager.svelte:1053", swift: "Views/LibraryView.swift", marker: "selected ? \"作品の選択を解除\" : \"作品を選択\""),
    .init(web: "HistoryManager.svelte:1054", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyGenerationTitle\""),
    .init(web: "HistoryManager.svelte:1056", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPreviewTitle\""),
    .init(web: "HistoryManager.svelte:1063", swift: "Views/LibraryPresentation.swift", marker: "work.starred ? \"starOn\" : \"starOff\""),
    .init(web: "HistoryManager.svelte:1064", swift: "Views/LibraryPresentation.swift", marker: "marked ? \"forRevisionOn\" : \"forRevisionOff\""),
    .init(web: "HistoryManager.svelte:1067", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyTrashItemTitle\""),
    .init(web: "HistoryManager.svelte:1069", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyRestoreTitle\""),
    .init(web: "HistoryManager.svelte:1070", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPermanentDeleteTitle\""),
    .init(web: "HistoryManager.svelte:1094", swift: "Views/LibraryView.swift", marker: "selected ? \"作品の選択を解除\" : \"作品を選択\""),
    .init(web: "HistoryManager.svelte:1101", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyGenerationTitle\""),
    .init(web: "HistoryManager.svelte:1105", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPreviewTitle\""),
    .init(web: "HistoryManager.svelte:1123", swift: "Views/LibraryPresentation.swift", marker: "work.starred ? \"starOn\" : \"starOff\""),
    .init(web: "HistoryManager.svelte:1130", swift: "Views/LibraryPresentation.swift", marker: "marked ? \"forRevisionOn\" : \"forRevisionOff\""),
    .init(web: "HistoryManager.svelte:1134", swift: "Views/LibraryView.swift", marker: "inkuTooltip(hashCopyTooltip(hash))"),
    .init(web: "HistoryManager.svelte:1165", swift: "Views/LibraryView.swift", marker: "selected ? \"作品の選択を解除\" : \"作品を選択\""),
    .init(web: "HistoryManager.svelte:1171", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPreviewTitle\""),
    .init(web: "HistoryManager.svelte:1180", swift: "Views/LibraryPresentation.swift", marker: "work.starred ? \"starOn\" : \"starOff\""),
    .init(web: "HistoryManager.svelte:1198", swift: "Views/LibraryView.swift", marker: "inkuTooltip(hashCopyTooltip(hash))"),
    .init(web: "HistoryManager.svelte:1208", swift: "Views/LibraryPresentation.swift", marker: "marked ? \"forRevisionOn\" : \"forRevisionOff\""),
    .init(web: "HistoryManager.svelte:1212", excluded: "作品ごとの共有設定は単一利用者アプリに無い"),
    .init(web: "HistoryManager.svelte:1215", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyTrashItemTitle\""),
    .init(web: "HistoryManager.svelte:1225", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyRestoreTitle\""),
    .init(web: "HistoryManager.svelte:1226", swift: "Views/LibraryView.swift", marker: "serverKey: \"historyPermanentDeleteTitle\""),
    .init(web: "HistoryStrip.svelte:221", swift: "Views/HistoryStripView.swift", marker: "collapsed ? \"historyExpand\" : \"historyCollapse\""),
    .init(web: "HistoryStrip.svelte:266", swift: "Views/HistoryStripView.swift", marker: "tooltipValue(mark)"),
    .init(web: "HistoryStrip.svelte:272", swift: "Views/HistoryStripView.swift", marker: "work.starred ? \"starOn\" : \"starOff\""),
    .init(web: "HistoryStrip.svelte:282", swift: "Views/HistoryStripView.swift", marker: "tooltipValue(line.full)"),
    .init(web: "HistoryThumbnail.svelte:61", swift: "Views/ArtworkCanvas.swift", marker: "tooltipValue(label)"),
    .init(web: "InputPanel.svelte:182", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipInputTabSingle\""),
    .init(web: "InputPanel.svelte:211", swift: "Views/CreationView.swift", marker: "tip(\"次の作品の描画モデルを選びます。\")"),
    .init(web: "InputPanel.svelte:217", swift: "Views/CreationView.swift", marker: "tooltipValue(value)"),
    .init(web: "InputPanel.svelte:219", swift: "Views/CreationView.swift", marker: "tooltipValue(value)"),
    .init(web: "InputPanel.svelte:220", swift: "Views/CreationView.swift", marker: "tooltipValue(value)"),
    .init(web: "InputPanel.svelte:227", swift: "Views/CreationView.swift", marker: "tip(\"次の作品の配色を選びます。\")"),
    .init(web: "InputPanel.svelte:232", swift: "Views/CreationView.swift", marker: "tooltipValue(value)"),
    .init(web: "InputPanel.svelte:236", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipInputSketch\""),
    .init(web: "InputPanel.svelte:239", swift: "Views/CreationView.swift", marker: "tip(\"次の作品の筆致を規則から外します。\")"),
    .init(web: "InputPanel.svelte:250", swift: "Views/CreationView.swift", marker: "tip(\"用紙の形と意図を見て、次の作品の用紙を選びます。\")"),
    .init(web: "InputPanel.svelte:263", swift: "Views/BatchPanelView.swift", marker: "serverKey: \"tooltipInputClear\""),
    .init(web: "InputPanel.svelte:288", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipInputClear\""),
    .init(web: "InputPanel.svelte:332", swift: "Views/CreationView.swift", marker: "serverKey: \"tooltipForkDescription\""),
    .init(web: "InputPanel.svelte:336", swift: "Views/CreationView.swift", marker: "tip(\"入力と次の生成条件から作品を描きます。\")"),
    .init(web: "LineagePanel.svelte:734", swift: "Views/LineageView.swift", marker: "tip(\"チェックした作品をゴミ箱へ移動\")"),
    .init(web: "LineagePanel.svelte:740", swift: "Views/LineageView.swift", marker: "serverKey: \"okugakiTooltip\""),
    .init(web: "LineagePanel.svelte:800", swift: "Views/LibraryPresentation.swift", marker: "work.starred ? \"starOn\" : \"starOff\""),
    .init(web: "LineagePanel.svelte:810", swift: "Views/LibraryPresentation.swift", marker: "marked ? \"forRevisionOn\" : \"forRevisionOff\""),
    .init(web: "LineagePanel.svelte:819", swift: "Views/LineageView.swift", marker: "serverKey: \"descriptionLockedReason\""),
    .init(web: "LineagePanel.svelte:845", swift: "Views/LineageView.swift", marker: "tooltipValue(stageModelTitle(work))"),
    .init(web: "LineagePanel.svelte:853", swift: "Views/LineageView.swift", marker: "work.descriptionHash ?? \"\""),
    .init(web: "LineagePanel.svelte:894", swift: "Views/LibraryView.swift", marker: ": model.display.tooltip(\"描画ハッシュ全体をコピー\", serverKey: \"historyHashCopyTitle\")"),
    .init(web: "LineagePanel.svelte:903", swift: "Views/LibraryView.swift", marker: ": model.display.tooltip(\"描画ハッシュ全体をコピー\", serverKey: \"historyHashCopyTitle\")"),
    .init(web: "LineagePanel.svelte:948", swift: "Views/AuxiliaryView.swift", marker: "serverKey: \"okugakiDelete\""),
    .init(web: "ModelAdministrationSettings.svelte:579", swift: "Views/ModelSettingsDialogs.swift", marker: "serverKey: \"settingsModelFetchDisabledWhileDirty\""),
    .init(web: "OutputTabsContent.svelte:62", swift: "Views/CreationWorkInfoView.swift", marker: "serverKey: \"promptCopied\""),
    .init(web: "OutputTabsContent.svelte:94", swift: "Views/CreationWorkInfoView.swift", marker: "serverKey: \"promptCopied\""),
    .init(web: "OutputTabsContent.svelte:130", swift: "Views/CreationWorkInfoView.swift", marker: "serverKey: \"promptCopied\""),
    .init(web: "RefinementAdjustView.svelte:96", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipCanvasVaryComposition\""),
    .init(web: "RefinementAdjustView.svelte:107", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipCanvasVaryInterpretation\""),
    .init(web: "RefinementAdjustView.svelte:117", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipCanvasVaryPerformance\""),
    .init(web: "RefinementAdjustView.svelte:134", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipRefineSingle\""),
    .init(web: "RefinementAdjustView.svelte:144", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipVariationGridDefault\""),
    .init(web: "RefinementCandidateGrid.svelte:34", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipRefineDiscardAndClose\""),
    .init(web: "RefinementCandidateGrid.svelte:39", swift: "Views/RefinementView.swift", marker: "serverKey: \"tooltipVariationGridSaveSelected\""),
    .init(web: "RefinementCandidateGrid.svelte:63", swift: "Views/RefinementView.swift", marker: "tooltip(\"保存済み\")"),
    .init(web: "RefinementModelCompareView.svelte:58", swift: "Views/ComparisonView.swift", marker: "serverKey: \"tooltipModelCompare\""),
    .init(web: "RenderLimitsSettings.svelte:125", swift: "Views/OperationalLimitsView.swift", marker: "showTooltips ? tip : \"\""),
    .init(web: "SavedWorkExportMenu.svelte:173", swift: "Views/CreationControls.swift", marker: "serverKey: \"exportLabel\""),
    .init(web: "SavedWorkExportMenu.svelte:189", swift: "Views/ExportView.swift", marker: "tooltipValue(work.id)"),
    .init(web: "SavedWorkExportMenu.svelte:190", swift: "Views/ExportView.swift", marker: "tooltipValue(work.effectiveSourceText)"),
    .init(web: "SettingsModal.svelte:254", excluded: "表示設定の詳細ヒント（settingsDetailHint）は Server 設定画面のもので対象外"),
    .init(web: "SketchSelect.svelte:47", swift: "Views/WorkEditView.swift", marker: "tooltips: [model.display.tooltip(\"写生を通さず、記述だけで描く\")"),
    .init(web: "UnreadWordsPanel.svelte:48", swift: "Views/UnreadWordsView.swift", marker: "serverKey: \"settingsUnreadWordsPurposeTooltip\""),
    .init(web: "UnreadWordsPanel.svelte:88", swift: "Views/UnreadWordsView.swift", marker: "\"settingsUnreadWordsFirstSeen\""),
    .init(web: "UnreadWordsPanel.svelte:90", swift: "Views/UnreadWordsView.swift", marker: "tooltipValue(context)"),
    .init(web: "VariationLanes.svelte:85", swift: "Views/RefinementView.swift", marker: "\"候補 %ld\", slot.id) + \" · \""),
    .init(web: "WorkActionMenu.svelte:107", swift: "Views/CreationView.swift", marker: "serverKey: \"workActionGenerationLocked\""),
    .init(web: "WorkActionMenu.svelte:126", swift: "SavedWorkActionState.swift", marker: "tooltip(\"記述を変える\") : reason"),
    .init(web: "WorkActionMenu.svelte:130", swift: "SavedWorkActionState.swift", marker: "tooltip(\"写生なし／ありで描き直す\") : reason"),
    .init(web: "WorkActionMenu.svelte:131", swift: "SavedWorkActionState.swift", marker: "tooltip(\"モデルを変える\") : reason"),
]
